public enum Effect
{
    PlacePopulationCardFromPlayer,
    GrowHerbivoreEcosystem,
    GrowCarnivoreEcosystem,
    KillHerbivoreEcosystem,
    KillCarnivoreEcosystem,
    Discard,
    Draw2,
    Draw5,
    OverviewSwitch,
    GrowMushroomEcosystem,
    GrowMacrofungi,
    PlaceConstruction,
    PlaceInitialCards,
    PlayAndDiscardInfluenceCard,
    MovePopulationToEmptySlot,
    PlaceInfluenceOnPopulation,
    GiveRabies,
    DestroyAllInTerritory,
    DestroyNonFungiInTerritory,
    GrowMushroom,
    GrowMushroomEndOfAction,
    MakeOmnivore,
    GrowPlant,
    GrowPlantEndOfAction,
    KillPlacedCard,
    ObserveSeededFruit,
    ObserveDeepRoots,
    ObserveGreenIvy,
    ObserveMushroomPredator,
    ObserveParasite,
    
    RushEcosystemTurn,
    PutLeash,
    
}